# Generated by Django 5.2.4 on 2025-08-09 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_dataset_license_dataset_measurement_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreprocessJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='ジョブ名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('notebook_path', models.CharField(max_length=500, verbose_name='Notebookパス')),
                ('default_parameters', models.JSONField(default=dict, verbose_name='既定パラメータ')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '前処理ジョブ',
                'verbose_name_plural': '前処理ジョブ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(default=dict, verbose_name='実行パラメータ')),
                ('status', models.CharField(choices=[('PENDING', '待機中'), ('RUNNING', '実行中'), ('SUCCESS', '成功'), ('FAILED', '失敗')], default='PENDING', max_length=10)),
                ('log', models.TextField(blank=True, verbose_name='ログ')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('input_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_runs', to='ingest.rawdatafile')),
                ('output_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_job_runs', to='ingest.dataset')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ingest.preprocessjob')),
            ],
            options={
                'verbose_name': 'ジョブ実行',
                'verbose_name_plural': 'ジョブ実行',
                'ordering': ['-started_at'],
            },
        ),
    ]
