# Generated by Django 5.2.4 on 2025-08-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_preprocessjob_jobrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprocessjob',
            name='notebook_file',
            field=models.FileField(blank=True, null=True, upload_to='notebooks/', verbose_name='Notebookファイル'),
        ),
        migrations.AlterField(
            model_name='preprocessjob',
            name='notebook_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='Notebookパス'),
        ),
    ]
