# Generated by Django 5.2.4 on 2025-08-09 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0004_preprocessjob_notebook_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprocessjob',
            name='entry_function',
            field=models.CharField(default='process', max_length=100, verbose_name='エントリ関数名'),
        ),
        migrations.AddField(
            model_name='preprocessjob',
            name='job_type',
            field=models.CharField(choices=[('notebook', 'Notebook'), ('python', 'Python Script')], default='notebook', max_length=20, verbose_name='ジョブ種別'),
        ),
        migrations.AddField(
            model_name='preprocessjob',
            name='script_file',
            field=models.FileField(blank=True, null=True, upload_to='scripts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py'])], verbose_name='スクリプトファイル'),
        ),
        migrations.AddField(
            model_name='preprocessjob',
            name='script_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='スクリプトパス'),
        ),
    ]
