# Generated by Django 5.2.4 on 2025-07-31 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='テンプレート名')),
                ('template_type', models.CharField(choices=[('correlation', '相関分析'), ('time_series', '時系列分析'), ('statistical', '統計分析'), ('ml_exploration', '機械学習探索'), ('vehicle_performance', '車両性能分析'), ('custom', 'カスタム分析')], max_length=30, verbose_name='テンプレート種類')),
                ('description', models.TextField(verbose_name='説明')),
                ('required_columns', models.JSONField(verbose_name='必須カラム')),
                ('optional_columns', models.JSONField(default=list, verbose_name='オプションカラム')),
                ('analysis_config', models.JSONField(verbose_name='分析設定')),
                ('output_charts', models.JSONField(verbose_name='出力グラフ設定')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用回数')),
                ('is_public', models.BooleanField(default=False, verbose_name='公開設定')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '分析テンプレート',
                'verbose_name_plural': '分析テンプレート',
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='グラフタイトル')),
                ('chart_type', models.CharField(choices=[('line', '線グラフ'), ('bar', '棒グラフ'), ('scatter', '散布図'), ('histogram', 'ヒストグラム'), ('box', 'ボックスプロット'), ('heatmap', 'ヒートマップ'), ('pie', '円グラフ'), ('area', 'エリアグラフ'), ('violin', 'バイオリンプロット'), ('3d_scatter', '3D散布図')], max_length=20, verbose_name='グラフ種類')),
                ('x_axis_column', models.CharField(max_length=255, verbose_name='X軸カラム')),
                ('y_axis_column', models.CharField(max_length=255, verbose_name='Y軸カラム')),
                ('z_axis_column', models.CharField(blank=True, max_length=255, verbose_name='Z軸カラム（3D用）')),
                ('color_column', models.CharField(blank=True, max_length=255, verbose_name='色分けカラム')),
                ('size_column', models.CharField(blank=True, max_length=255, verbose_name='サイズカラム')),
                ('chart_config', models.JSONField(default=dict, verbose_name='グラフ設定')),
                ('color_scheme', models.CharField(default='viridis', max_length=50, verbose_name='カラースキーム')),
                ('filters', models.JSONField(default=dict, verbose_name='データフィルター')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_public', models.BooleanField(default=False, verbose_name='公開設定')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='ingest.dataset')),
            ],
            options={
                'verbose_name': 'グラフ',
                'verbose_name_plural': 'グラフ',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ダッシュボード名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('layout_config', models.JSONField(default=dict, verbose_name='レイアウト設定')),
                ('auto_refresh_interval', models.IntegerField(blank=True, null=True, verbose_name='自動更新間隔（秒）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_public', models.BooleanField(default=False, verbose_name='公開設定')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': 'ダッシュボード',
                'verbose_name_plural': 'ダッシュボード',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_x', models.IntegerField(verbose_name='X座標')),
                ('grid_y', models.IntegerField(verbose_name='Y座標')),
                ('grid_width', models.IntegerField(default=1, verbose_name='幅')),
                ('grid_height', models.IntegerField(default=1, verbose_name='高さ')),
                ('display_order', models.IntegerField(verbose_name='表示順序')),
                ('is_visible', models.BooleanField(default=True, verbose_name='表示/非表示')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.chart')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.dashboard')),
            ],
            options={
                'verbose_name': 'ダッシュボードグラフ',
                'verbose_name_plural': 'ダッシュボードグラフ',
                'ordering': ['dashboard', 'display_order'],
                'unique_together': {('dashboard', 'chart')},
            },
        ),
        migrations.AddField(
            model_name='dashboard',
            name='charts',
            field=models.ManyToManyField(through='visualization.DashboardChart', to='visualization.chart', verbose_name='含まれるグラフ'),
        ),
        migrations.CreateModel(
            name='DataComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='比較分析名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('comparison_columns', models.JSONField(verbose_name='比較対象カラム')),
                ('comparison_config', models.JSONField(default=dict, verbose_name='比較設定')),
                ('comparison_results', models.JSONField(blank=True, null=True, verbose_name='比較結果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('datasets', models.ManyToManyField(to='ingest.dataset', verbose_name='比較データセット')),
            ],
            options={
                'verbose_name': 'データ比較',
                'verbose_name_plural': 'データ比較',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_chart_type', models.CharField(default='line', max_length=20, verbose_name='デフォルトグラフ種類')),
                ('default_color_scheme', models.CharField(default='viridis', max_length=50, verbose_name='デフォルトカラースキーム')),
                ('items_per_page', models.IntegerField(default=20, verbose_name='ページあたり項目数')),
                ('dashboard_preferences', models.JSONField(default=dict, verbose_name='ダッシュボード設定')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='メール通知')),
                ('data_quality_alerts', models.BooleanField(default=True, verbose_name='データ品質アラート')),
                ('custom_theme', models.JSONField(default=dict, verbose_name='カスタムテーマ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザー設定',
                'verbose_name_plural': 'ユーザー設定',
            },
        ),
    ]
