# Generated by Django 5.2.4 on 2025-07-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='description',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
    ]
