# Generated by Django 5.2.4 on 2025-11-06 08:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingest", "0005_preprocessjob_entry_function_preprocessjob_job_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("raw", "Raw"),
                            ("curated", "Curated"),
                            ("analytics", "Analytics"),
                            ("feature", "Feature Store"),
                        ],
                        default="curated",
                        max_length=20,
                    ),
                ),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("deprecated", "Deprecated"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "data_classification",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal"),
                            ("confidential", "Confidential"),
                            ("restricted", "Restricted"),
                        ],
                        default="internal",
                        max_length=20,
                    ),
                ),
                ("refresh_cadence", models.CharField(blank=True, max_length=120)),
                ("retention_days", models.PositiveIntegerField(blank=True, null=True)),
                ("governance_policies", models.TextField(blank=True)),
                ("lineage_summary", models.TextField(blank=True)),
                ("record_count", models.BigIntegerField(default=0)),
                (
                    "data_volume_mb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "quality_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("last_validated_at", models.DateTimeField(blank=True, null=True)),
                ("tags", models.CharField(blank=True, max_length=255)),
                (
                    "dataset",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_asset",
                        to="ingest.dataset",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "steward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stewarded_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "データアセット",
                "verbose_name_plural": "データアセット",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DataContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("consumer_team", models.CharField(max_length=255)),
                ("contract_summary", models.TextField(blank=True)),
                ("sla_description", models.TextField(blank=True)),
                ("refresh_schedule", models.CharField(blank=True, max_length=120)),
                ("delivery_channel", models.CharField(blank=True, max_length=255)),
                ("escalation_contact", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="base.dataasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "データ契約",
                "verbose_name_plural": "データ契約",
                "ordering": ["consumer_team"],
            },
        ),
        migrations.CreateModel(
            name="DataDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "criticality",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("default_retention_days", models.PositiveIntegerField(default=365)),
                (
                    "business_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_domains",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_steward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stewarded_domains",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "データドメイン",
                "verbose_name_plural": "データドメイン",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="dataasset",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="base.datadomain",
            ),
        ),
        migrations.CreateModel(
            name="DataMetricSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metric_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("total_records", models.BigIntegerField(default=0)),
                ("valid_records", models.BigIntegerField(default=0)),
                ("invalid_records", models.BigIntegerField(default=0)),
                ("duplicate_records", models.BigIntegerField(default=0)),
                ("freshness_lag_hours", models.FloatField(blank=True, null=True)),
                ("completeness_percent", models.FloatField(blank=True, null=True)),
                ("uniqueness_percent", models.FloatField(blank=True, null=True)),
                ("quality_score", models.FloatField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_snapshots",
                        to="base.dataasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "データメトリクス",
                "verbose_name_plural": "データメトリクス",
                "ordering": ["-metric_date"],
            },
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("database", "Database"),
                            ("stream", "Stream"),
                            ("file", "File Upload"),
                            ("external", "External API"),
                            ("manual", "Manual"),
                        ],
                        default="file",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("technical_contact", models.CharField(blank=True, max_length=255)),
                ("ingestion_frequency", models.CharField(blank=True, max_length=100)),
                ("connection_details", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sources",
                        to="base.datadomain",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "データソース",
                "verbose_name_plural": "データソース",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="dataasset",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="base.datasource",
            ),
        ),
        migrations.CreateModel(
            name="DataColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("data_type", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("business_definition", models.TextField(blank=True)),
                ("is_nullable", models.BooleanField(default=True)),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("identifier", "Identifier"),
                            ("sensitive", "Sensitive"),
                            ("general", "General"),
                            ("derived", "Derived"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("quality_rules", models.JSONField(blank=True, default=dict)),
                ("sample_values", models.JSONField(blank=True, default=list)),
                ("stat_min", models.FloatField(blank=True, null=True)),
                ("stat_max", models.FloatField(blank=True, null=True)),
                ("stat_mean", models.FloatField(blank=True, null=True)),
                ("stat_distinct", models.IntegerField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="base.dataasset",
                    ),
                ),
                (
                    "schema_field",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_column",
                        to="ingest.dataschema",
                    ),
                ),
            ],
            options={
                "verbose_name": "データカラム",
                "verbose_name_plural": "データカラム",
                "ordering": ["asset", "name"],
                "unique_together": {("asset", "name")},
            },
        ),
        migrations.CreateModel(
            name="DataLineage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transformation_type",
                    models.CharField(
                        choices=[
                            ("ingest", "Ingestion"),
                            ("transform", "Transformation"),
                            ("join", "Join"),
                            ("aggregate", "Aggregation"),
                            ("manual", "Manual"),
                        ],
                        default="transform",
                        max_length=20,
                    ),
                ),
                ("transformation_description", models.TextField(blank=True)),
                ("impact_notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "downstream_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upstream_links",
                        to="base.dataasset",
                    ),
                ),
                (
                    "upstream_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downstream_links",
                        to="base.dataasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "データリネージ",
                "verbose_name_plural": "データリネージ",
                "unique_together": {
                    ("upstream_asset", "downstream_asset", "transformation_type")
                },
            },
        ),
        migrations.AlterUniqueTogether(
            name="dataasset",
            unique_together={("name", "domain")},
        ),
    ]
